[package]
name = "rust_spreadsheet"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1.11.1"
eframe = "0.31.1"
egui = "0.31.1"
chrono = "0.4.26"
egui_extras = {version = "0.31.1", features = ["all_loaders"] }
image = {version = "0.25.6", features = ["jpeg", "png"]}
